/**
 * ============================================================
 * ThermalEyes 固件主程序 | ThermalEyes Firmware Main Program
 * ============================================================
 * 平台 | Platform: STM32F411CEU6 (Black Pill 开发板)
 * 功能 | Function:
 *   1. 通过 I2C 读取 MLX90640 热成像传感器数据
 *      Read MLX90640 thermal sensor data via I2C
 *   2. 将温度数据打包并通过 USB CDC 发送到手机
 *      Package temperature data and send to phone via USB CDC
 *   3. 与可见光摄像头并行工作，完成双目热成像数据采集
 *      Work in parallel with visible camera for binocular thermal data acquisition
 *
 * 开源参考 | Open-source reference:
 *   https://github.com/colourfate/thermal_bridge
 *
 * 开发环境 | Development Environment:
 *   - STM32CubeIDE 1.14+
 *   - STM32CubeMX (用于初始化代码生成 | for init code generation)
 *   - HAL 库 | HAL Library
 *
 * 硬件连接 | Hardware Connections:
 *   MLX90640 SCL -> PB6 (I2C1_SCL)
 *   MLX90640 SDA -> PB7 (I2C1_SDA)
 *   USB D+      -> PA12
 *   USB D-      -> PA11
 * ============================================================
 */

/* ============================================================
 * 头文件包含 | Header Includes
 * ============================================================ */
#include "main.h"
#include "mlx90640.h"
#include "usb_cdc.h"

/* STM32 HAL 库 | STM32 HAL Library */
/* 在 STM32CubeIDE 中这些头文件由 CubeMX 自动生成 */
/* In STM32CubeIDE, these headers are auto-generated by CubeMX */
#include "stm32f4xx_hal.h"
#include "i2c.h"
#include "usbd_core.h"
#include "usbd_desc.h"
#include "usbd_cdc.h"
#include "usbd_cdc_if.h"

/* 标准库 | Standard Library */
#include <string.h>
#include <stdio.h>
#include <stdint.h>

/* ============================================================
 * 私有宏定义 | Private Macro Definitions
 * ============================================================ */

/* 系统时钟频率 | System clock frequency */
#define SYS_CLOCK_FREQ       100000000U  /* 100 MHz (STM32F411 最大频率 | STM32F411 max frequency) */

/* 主循环延时 | Main loop delay */
#define MAIN_LOOP_DELAY_MS   10          /* 主循环间隔 (ms) | Main loop interval */

/* LED 指示灯引脚 | LED indicator pin */
#define LED_PIN              GPIO_PIN_13
#define LED_PORT             GPIOC

/* 错误代码 | Error codes */
#define ERR_NONE             0
#define ERR_I2C_INIT         1
#define ERR_SENSOR_INIT      2
#define ERR_USB_INIT         3
#define ERR_FRAME_READ       4

/* ============================================================
 * 私有变量 | Private Variables
 * ============================================================ */

/* I2C 句柄 - 由 CubeMX 生成 | I2C handle - generated by CubeMX */
I2C_HandleTypeDef hi2c1;

/* USB 设备句柄 | USB device handle */
USBD_HandleTypeDef hUsbDeviceFS;

/* MLX90640 帧缓冲区 | MLX90640 frame buffer */
/* 每帧 32x24 = 768 像素，每个像素 2 字节温度数据 */
/* Each frame: 32x24 = 768 pixels, 2 bytes temperature data per pixel */
static uint16_t thermal_frame[MLX90640_PIXEL_COUNT];

/* 发送数据缓冲区 | Transmit data buffer */
/* 帧头(2B) + 帧计数(2B) + 温度数据(768*2=1536B) + 校验(2B) = 1542B */
/* Header(2B) + frame_count(2B) + temp_data(768*2=1536B) + checksum(2B) = 1542B */
static uint8_t tx_buffer[USB_TX_BUFFER_SIZE];

/* 帧计数器 | Frame counter */
static uint16_t frame_count = 0;

/* 系统状态标志 | System status flags */
static volatile uint8_t sensor_ready = 0;
static volatile uint8_t usb_ready = 0;
static volatile uint8_t error_state = ERR_NONE;

/* 调试用 UART 缓冲区 | Debug UART buffer */
#ifdef ENABLE_DEBUG_UART
static char debug_buf[128];
#endif

/* ============================================================
 * 私有函数声明 | Private Function Declarations
 * ============================================================ */
static void SystemClock_Config(void);
static void GPIO_Init(void);
static void I2C1_Init(void);
static void Error_Handler(uint8_t err_code);
static void Blink_LED(uint8_t count, uint32_t period_ms);

/* ============================================================
 * 主函数 | Main Function
 * ============================================================ */

/**
 * @brief 主函数入口 | Main entry point
 *
 * 初始化流程 | Initialization sequence:
 *   1. HAL 库初始化 | HAL library init
 *   2. 系统时钟配置 | System clock config
 *   3. GPIO 初始化 (LED) | GPIO init (LED)
 *   4. I2C 初始化 | I2C init
 *   5. USB CDC 初始化 | USB CDC init
 *   6. MLX90640 传感器初始化 | MLX90640 sensor init
 *   7. 进入主循环 | Enter main loop
 */
int main(void)
{
    /* ---- 第一步: HAL 库初始化 ---- */
    /* Step 1: HAL library initialization */
    HAL_Init();

    /* ---- 第二步: 配置系统时钟 ---- */
    /* Step 2: Configure system clock */
    /* STM32F411: 使用 HSE (外部晶振 8MHz) 通过 PLL 倍频到 100MHz */
    /* STM32F411: Use HSE (external 8MHz crystal), PLL to 100MHz */
    SystemClock_Config();

    /* ---- 第三步: GPIO 初始化 ---- */
    /* Step 3: GPIO initialization (LED on PC13) */
    GPIO_Init();

    /* 启动指示: 快闪 3 次 | Startup indicator: blink 3 times fast */
    Blink_LED(3, 100);

    /* ---- 第四步: I2C 初始化 ---- */
    /* Step 4: I2C initialization */
    I2C1_Init();

    /* ---- 第五步: USB CDC 初始化 ---- */
    /* Step 5: USB CDC initialization */
    /* 初始化 USB 设备并注册 CDC 类 | Init USB device and register CDC class */
    if (USBD_Init(&hUsbDeviceFS, &FS_Desc, DEVICE_FS) != USBD_OK) {
        Error_Handler(ERR_USB_INIT);
    }
    if (USBD_RegisterClass(&hUsbDeviceFS, &USBD_CDC) != USBD_OK) {
        Error_Handler(ERR_USB_INIT);
    }
    if (USBD_CDC_RegisterInterface(&hUsbDeviceFS, &USBD_Interface_fops_FS) != USBD_OK) {
        Error_Handler(ERR_USB_INIT);
    }
    if (USBD_Start(&hUsbDeviceFS) != USBD_OK) {
        Error_Handler(ERR_USB_INIT);
    }

    /* 等待 USB 枚举完成 | Wait for USB enumeration */
    HAL_Delay(500);
    usb_ready = 1;

    /* ---- 第六步: MLX90640 传感器初始化 ---- */
    /* Step 6: MLX90640 sensor initialization */
    if (MLX90640_Init(&hi2c1, MLX90640_I2C_ADDR) != MLX90640_OK) {
        Error_Handler(ERR_SENSOR_INIT);
    }
    sensor_ready = 1;

    /* 初始化成功指示: 慢闪 2 次 | Init success: blink 2 times slow */
    Blink_LED(2, 300);

    /* ---- 第七步: 主循环 ---- */
    /* Step 7: Main loop */
    while (1)
    {
        /* 检查系统和传感器状态 | Check system and sensor status */
        if (!sensor_ready || !usb_ready) {
            HAL_Delay(MAIN_LOOP_DELAY_MS);
            continue;
        }

        /* 读取一帧热成像数据 | Read one frame of thermal data */
        /* MLX90640 需要读取两个子页才能组成完整的一帧 */
        /* MLX90640 requires reading two sub-pages for a complete frame */
        if (MLX90640_ReadFrame(&hi2c1, thermal_frame) == MLX90640_OK)
        {
            /* 打包数据并通过 USB CDC 发送 */
            /* Package data and send via USB CDC */
            USB_CDC_SendThermalFrame(thermal_frame, frame_count);

            /* 更新帧计数器 | Update frame counter */
            frame_count++;

            /* LED 闪烁指示数据传输 | LED blink to indicate data transfer */
            HAL_GPIO_TogglePin(LED_PORT, LED_PIN);
        }
        else
        {
            /* 帧读取错误 | Frame read error */
            error_state = ERR_FRAME_READ;
        }

        /* 主循环延时 | Main loop delay */
        HAL_Delay(MAIN_LOOP_DELAY_MS);
    }
}

/* ============================================================
 * 系统时钟配置 | System Clock Configuration
 * ============================================================ */

/**
 * @brief 配置系统时钟 | Configure system clock
 *
 * STM32F411 时钟树配置:
 *   HSE = 8MHz (外部晶振 | external crystal)
 *   PLLM = 4, PLLN = 100, PLLP = 2
 *   SYSCLK = 8MHz * 100 / 4 / 2 = 100MHz
 *   AHB  = SYSCLK / 1 = 100MHz
 *   APB1 = SYSCLK / 2 = 50MHz  (I2C 挂在 APB1 上 | I2C on APB1)
 *   APB2 = SYSCLK / 1 = 100MHz
 *
 * 注意: 在实际项目中此函数由 STM32CubeMX 自动生成
 * Note: In a real project this function is auto-generated by STM32CubeMX
 */
static void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    /* 配置电压调节器输出 | Configure voltage regulator output */
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    /* 配置 HSE 和 PLL | Configure HSE and PLL */
    RCC_OscInitStruct.OscillatorType      = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState            = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState        = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource       = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLM            = 4;    /* HSE/PLLm = 8/4 = 2MHz */
    RCC_OscInitStruct.PLL.PLLN            = 100;  /* 2MHz * 100 = 200MHz VCO */
    RCC_OscInitStruct.PLL.PLLP            = RCC_PLLP_DIV2; /* 200/2 = 100MHz */
    RCC_OscInitStruct.PLL.PLLQ            = 8;    /* 200/8 = 25MHz (USB 需要 48MHz) */

    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
        Error_Handler(ERR_I2C_INIT);  /* 时钟配置失败 | Clock config failed */
    }

    /* 配置系统时钟源和分频 | Configure system clock source and dividers */
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                 | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;  /* 100MHz */
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;          /* 100MHz */
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;            /* 50MHz */
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;            /* 100MHz */

    /* Flash 等待周期 | Flash wait states */
    /* 100MHz 需要 3 个等待周期 | 100MHz requires 3 wait states */
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_3) != HAL_OK) {
        Error_Handler(ERR_I2C_INIT);
    }
}

/* ============================================================
 * GPIO 初始化 | GPIO Initialization
 * ============================================================ */

/**
 * @brief 初始化 GPIO | Initialize GPIO
 *
 * PC13 - 板载 LED (低电平点亮 | Active low)
 */
static void GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* 使能 GPIOC 时钟 | Enable GPIOC clock */
    __HAL_RCC_GPIOC_CLK_ENABLE();

    /* 配置 LED 引脚 | Configure LED pin */
    GPIO_InitStruct.Pin   = LED_PIN;
    GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;  /* 推挽输出 | Push-pull output */
    GPIO_InitStruct.Pull  = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(LED_PORT, &GPIO_InitStruct);

    /* 初始状态: LED 熄灭 (高电平) | Initial state: LED off (high) */
    HAL_GPIO_WritePin(LED_PORT, LED_PIN, GPIO_PIN_SET);
}

/* ============================================================
 * I2C 初始化 | I2C Initialization
 * ============================================================ */

/**
 * @brief 初始化 I2C1 总线 | Initialize I2C1 bus
 *
 * I2C1 配置:
 *   时钟频率: 400kHz (Fast Mode)
 *   引脚: PB6 (SCL), PB7 (SDA)
 *
 * 注意: 在实际项目中此函数由 STM32CubeMX 自动生成
 * Note: In a real project this function is auto-generated by STM32CubeMX
 */
static void I2C1_Init(void)
{
    hi2c1.Instance             = I2C1;
    hi2c1.Init.ClockSpeed      = 400000;             /* 400kHz Fast Mode */
    hi2c1.Init.DutyCycle       = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1     = 0;
    hi2c1.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;

    if (HAL_I2C_Init(&hi2c1) != HAL_OK) {
        Error_Handler(ERR_I2C_INIT);
    }

    /* 使能 I2C 模拟滤波器 | Enable I2C analog filter */
    if (HAL_I2CEx_ConfigAnalogFilter(&hi2c1, I2C_ANALOGFILTER_ENABLE) != HAL_OK) {
        Error_Handler(ERR_I2C_INIT);
    }
}

/* ============================================================
 * 错误处理 | Error Handling
 * ============================================================ */

/**
 * @brief 错误处理函数 | Error handler function
 *
 * 通过 LED 闪烁次数指示错误类型
 * Indicate error type by LED blink count
 *
 * @param err_code 错误代码 | Error code
 */
static void Error_Handler(uint8_t err_code)
{
    error_state = err_code;

    /* 无限循环，LED 闪烁指示错误类型 | Infinite loop, LED blinks to indicate error */
    while (1)
    {
        Blink_LED(err_code, 200);
        HAL_Delay(1000);
    }
}

/**
 * @brief LED 闪烁函数 | LED blink function
 *
 * @param count    闪烁次数 | Number of blinks
 * @param period_ms 每次闪烁周期 (ms) | Blink period per cycle (ms)
 */
static void Blink_LED(uint8_t count, uint32_t period_ms)
{
    for (uint8_t i = 0; i < count; i++)
    {
        HAL_GPIO_WritePin(LED_PORT, LED_PIN, GPIO_PIN_RESET);  /* LED 亮 | On */
        HAL_Delay(period_ms / 2);
        HAL_GPIO_WritePin(LED_PORT, LED_PIN, GPIO_PIN_SET);    /* LED 灭 | Off */
        HAL_Delay(period_ms / 2);
    }
}

/* ============================================================
 * HAL 回调函数 | HAL Callback Functions
 * ============================================================ */

/**
 * @brief SysTick 中断回调 | SysTick interrupt callback
 *
 * 每 1ms 调用一次，用于 HAL 内部计时
 * Called every 1ms for HAL internal timing
 */
void SysTick_Handler(void)
{
    HAL_IncTick();
}

/**
 * @brief I2C 错误回调 | I2C error callback
 */
void HAL_I2C_ErrorCallback(I2C_HandleTypeDef *hi2c)
{
    /* I2C 总线错误恢复: 重置 I2C 外设 */
    /* I2C bus error recovery: reset I2C peripheral */
    HAL_I2C_DeInit(hi2c);
    HAL_I2C_Init(hi2c);
}
